name: CI

#different types of events webhook, scheduled, repository_dispatch (using github apis).
on:
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    #types: ["assigned, re-opened"]
    #https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
  #schedule: 
    #runs on cron expression and utc time.
    #- cron: '*/15 * * * *'
  #to trigger custom repository event send POST event to Github API Endpoint and add repository_dispatcg with types in your workflow file.

  workflow_dispatch:

jobs:
   build:
   #runners - self hosted & github hosted.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a hello world script
      #with for repo secrets
        env: 
          super_secret: ${{secrets.MySecret}}
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


    #default secret -github_token : access token used to authenticate on behalf of github app installed on your repo.
    #eg ${{secretes.GITHUB_TOKEN}}.
    #actions - reusable unit of code. to use it include it as a step in a workflow run.
    #events - specific activies that trigger workflow run. provide single event an array of event. 
    #runners (runs-on) - Self hosted & GITHUB hosted. only run one job at a time. 
    #JOB - consist a one or more steps can run independently or sequentially. 
    #step - set of tasks exceuted by job.
    #GITHUB Actions - name of overall process.



